/** Column headers and sample rows for client bulk-migration spreadsheets. */

export const CUSTOMER_BULK_HEADERS = [
  "full_name",
  "email",
  "mobile",
  "temporary_password",
  "gender",
  "date_of_birth",
  "dietary_preference",
  "allergies",
  "has_medical_history",
  "medical_history_notes",
  "address1_tag",
  "address1_street_1",
  "address1_street_2",
  "address1_landmark",
  "address1_city",
  "address1_state",
  "address1_pincode",
  "address1_is_primary",
  "address1_lat",
  "address1_lng",
  "address2_tag",
  "address2_street_1",
  "address2_street_2",
  "address2_landmark",
  "address2_city",
  "address2_state",
  "address2_pincode",
  "address2_is_primary",
  "address2_lat",
  "address2_lng",
] as const;

export const SUBSCRIPTION_BULK_HEADERS = [
  "customer_email",
  "customer_mobile",
  "subscription_mode",
  "plan_code",
  "start_date",
  "end_date",
  "base_price",
  "tax_percent",
  "pause_credits",
  "meal_category_code",
  "delivery_address",
  "payment_status",
  "payment_reference",
  "payment_notes",
] as const;

export const CUSTOMER_BULK_SAMPLE_ROWS: Record<string, string>[] = [
  {
    full_name: "Rahul Sharma",
    email: "rahul@example.com",
    mobile: "9876543210",
    temporary_password: "Welcome@2026",
    gender: "MALE",
    date_of_birth: "1990-05-15",
    dietary_preference: "Veg",
    allergies: "No peanuts",
    has_medical_history: "NO",
    medical_history_notes: "",
    address1_tag: "Home",
    address1_street_1: "Flat 4B Emerald Heights",
    address1_street_2: "Jubilee Hills",
    address1_landmark: "Near Apollo",
    address1_city: "Hyderabad",
    address1_state: "Telangana",
    address1_pincode: "500033",
    address1_is_primary: "YES",
    address1_lat: "",
    address1_lng: "",
    address2_tag: "",
    address2_street_1: "",
    address2_street_2: "",
    address2_landmark: "",
    address2_city: "",
    address2_state: "",
    address2_pincode: "",
    address2_is_primary: "",
    address2_lat: "",
    address2_lng: "",
  },
  {
    full_name: "Priya Nair",
    email: "priya@example.com",
    mobile: "9123456780",
    temporary_password: "Welcome@2026",
    gender: "FEMALE",
    date_of_birth: "",
    dietary_preference: "Non-Veg",
    allergies: "",
    has_medical_history: "NO",
    medical_history_notes: "",
    address1_tag: "Home",
    address1_street_1: "12 Green Park Road",
    address1_street_2: "",
    address1_landmark: "",
    address1_city: "Hyderabad",
    address1_state: "Telangana",
    address1_pincode: "500081",
    address1_is_primary: "YES",
    address1_lat: "",
    address1_lng: "",
    address2_tag: "",
    address2_street_1: "",
    address2_street_2: "",
    address2_landmark: "",
    address2_city: "",
    address2_state: "",
    address2_pincode: "",
    address2_is_primary: "",
    address2_lat: "",
    address2_lng: "",
  },
];

export const SUBSCRIPTION_BULK_SAMPLE_ROWS: Record<string, string>[] = [
  {
    customer_email: "rahul@example.com",
    customer_mobile: "9876543210",
    subscription_mode: "EXISTING",
    plan_code: "PLAN_30",
    start_date: "2026-06-05",
    end_date: "",
    base_price: "",
    tax_percent: "",
    pause_credits: "",
    meal_category_code: "VEG",
    delivery_address: "1",
    payment_status: "Payment Collected",
    payment_reference: "UPI-REF-001",
    payment_notes: "Migrated batch June 2026",
  },
  {
    customer_email: "priya@example.com",
    customer_mobile: "9123456780",
    subscription_mode: "CUSTOM",
    plan_code: "",
    start_date: "2026-06-05",
    end_date: "2026-07-20",
    base_price: "8500",
    tax_percent: "5",
    pause_credits: "2",
    meal_category_code: "CHICKEN",
    delivery_address: "1",
    payment_status: "Payment Pending",
    payment_reference: "",
    payment_notes: "Legacy partial term",
  },
];

export const REFERENCE_PLANS_HEADERS = [
  "plan_code",
  "plan_name",
  "duration_days",
  "pause_credits",
  "price_inr",
] as const;

export const REFERENCE_MEALS_HEADERS = ["meal_category_code", "meal_category_name"] as const;
