// src/services/__tests__/eligibilityChecker.property.test.ts
// Feature: customer-mobile-onboarding, Property 2: Eligibility decision is exactly-one-allowed-customer
//
// Property 2: Eligibility decision is exactly-one-allowed-customer — For any
// set of user/customer records and any submitted mobile, the eligibility check
// returns `eligible` IF AND ONLY IF the normalized mobile is associated with
// exactly one record whose role is `CUSTOMER` and whose onboarding_status is
// `IN_PROGRESS` or `COMPLETED`; zero matches yield `NOT_REGISTERED`, a
// non-allowed status yields `BAD_STATUS`, more than one match yields
// `AMBIGUOUS`, and in every non-eligible case no OTP is sent and no session is
// created.
//
// APPROACH: The service under test (`src/services/EligibilityChecker.ts`)
// composes the PURE `normalizeMobile` helper with the data-access
// `findCustomerByMobile`. We mock ONLY the repository with an in-memory record
// set generated by fast-check (varying role, onboarding_status, profile
// presence, and count) so the decision logic is exercised in isolation across
// many inputs. The checker performs no OTP/session side effects — we assert it
// only returns a decision object and never touches anything but the mocked
// lookup.
//
// Validates: Requirements 3.1, 3.4, 3.5, 9.6, 9.9, 12.1, 12.2, 12.3, 12.4

import { describe, it, expect, vi, beforeEach } from "vitest";
import * as fc from "fast-check";

// Mock the data-access layer. Replacing the whole module keeps its Supabase /
// `server-only` imports out of the test and lets each run inject a generated
// record set. `normalizeMobile` (pure) stays real, so real normalization drives
// the decision.
vi.mock("@/repositories/customerOnboardingRepository", () => ({
  findCustomerByMobile: vi.fn(),
}));

import { findCustomerByMobile } from "@/repositories/customerOnboardingRepository";
import { check } from "@/services/EligibilityChecker";
import type { CustomerLookup } from "@/repositories/customerOnboardingRepository";

// ─── Reference constants (re-stated independently of the implementation) ─────
const CUSTOMER_ROLE = "CUSTOMER";
const ALLOWED_STATUSES = ["IN_PROGRESS", "COMPLETED"] as const;

// ─── Arbitraries ──────────────────────────────────────────────────────────────

// A canonical 10-digit Indian mobile (first digit 6-9) — always passes
// `normalizeMobile`, so these runs exercise the association logic (not the
// format short-circuit).
const arbCanonicalMobile: fc.Arbitrary<string> = fc
  .tuple(
    fc.integer({ min: 6, max: 9 }),
    fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 9, maxLength: 9 })
  )
  .map(([first, rest]) => `${first}${rest.join("")}`);

// Roles: CUSTOMER plus non-CUSTOMER roles (which must be excluded, Req 3.5) and
// a null role.
const arbRole: fc.Arbitrary<string | null> = fc.constantFrom(
  "CUSTOMER",
  "ADMIN",
  "RIDER",
  "MASTER",
  null
);

// Onboarding statuses: the two allowed states plus non-allowed values and null.
const arbStatus: fc.Arbitrary<string | null> = fc.constantFrom(
  "IN_PROGRESS",
  "COMPLETED",
  "PENDING",
  "CANCELLED",
  "SUSPENDED",
  "",
  null
);

// A single lookup record. `profileId` and `onboardingStatus` are generated
// somewhat independently so the implementation's `profileId !== null` guard is
// also stressed (a status with no resolvable profile id must not count).
const arbRecord: fc.Arbitrary<CustomerLookup> = fc.record({
  userId: fc.uuid(),
  roleCode: arbRole,
  mobile: fc.option(arbCanonicalMobile, { nil: null }),
  profileId: fc.option(fc.uuid(), { nil: null }),
  onboardingStatus: arbStatus,
  email: fc.option(fc.emailAddress(), { nil: null }),
  isTestEmail: fc.boolean(),
});

// 0..n records sharing the submitted mobile.
const arbRecords: fc.Arbitrary<CustomerLookup[]> = fc.array(arbRecord, {
  minLength: 0,
  maxLength: 5,
});

// ─── Reference oracle (mirrors the decision table, order-preserving) ─────────
type Expected =
  | { eligible: true; profileId: string; status: string }
  | {
      eligible: false;
      reason: "NOT_REGISTERED" | "BAD_STATUS" | "AMBIGUOUS";
    };

function expectedDecision(records: CustomerLookup[]): Expected {
  const customerRecords = records.filter((r) => r.roleCode === CUSTOMER_ROLE);

  // No CUSTOMER record at all → not registered (Req 3.4, 12.1).
  if (customerRecords.length === 0) {
    return { eligible: false, reason: "NOT_REGISTERED" };
  }

  // Allowed = CUSTOMER + allowed status + resolvable profile id.
  const allowed = customerRecords.filter(
    (r) =>
      r.onboardingStatus !== null &&
      (ALLOWED_STATUSES as readonly string[]).includes(r.onboardingStatus) &&
      r.profileId !== null
  );

  if (allowed.length > 1) {
    return { eligible: false, reason: "AMBIGUOUS" }; // Req 3.6, 12.4
  }
  if (allowed.length === 0) {
    return { eligible: false, reason: "BAD_STATUS" }; // Req 3.4
  }
  return {
    eligible: true,
    profileId: allowed[0].profileId as string,
    status: allowed[0].onboardingStatus as string,
  }; // Req 3.1, 3.3
}

describe("Property 2: Eligibility decision is exactly-one-allowed-customer", () => {
  beforeEach(() => {
    vi.mocked(findCustomerByMobile).mockReset();
  });

  it("returns eligible iff exactly one allowed CUSTOMER record, else the correct reason", async () => {
    await fc.assert(
      fc.asyncProperty(arbCanonicalMobile, arbRecords, async (mobile, records) => {
        vi.mocked(findCustomerByMobile).mockResolvedValue(records);

        const result = await check(mobile);
        const expected = expectedDecision(records);

        expect(result.eligible).toBe(expected.eligible);
        if (expected.eligible && result.eligible) {
          expect(result.profileId).toBe(expected.profileId);
          expect(result.status).toBe(expected.status);
        } else if (!expected.eligible && !result.eligible) {
          expect(result.reason).toBe(expected.reason);
        }
      }),
      { numRuns: 25 }
    );
  });

  it("is a pure decision: non-eligible results carry only a reason (no profileId/status leaked, no OTP/session)", async () => {
    await fc.assert(
      fc.asyncProperty(arbCanonicalMobile, arbRecords, async (mobile, records) => {
        vi.mocked(findCustomerByMobile).mockResolvedValue(records);

        const result = await check(mobile);

        // The result is a plain decision object with only the expected keys —
        // there is no side-effect channel (no OTP token, no session handle).
        const keys = Object.keys(result).sort();
        if (result.eligible) {
          expect(keys).toEqual(["eligible", "profileId", "status"]);
        } else {
          expect(keys).toEqual(["eligible", "reason"]);
          // A rejected mobile never exposes a profile id or status.
          expect((result as Record<string, unknown>).profileId).toBeUndefined();
          expect((result as Record<string, unknown>).status).toBeUndefined();
        }
      }),
      { numRuns: 25 }
    );
  });

  it("rejects an invalid mobile format before any lookup (no side effect, no OTP)", async () => {
    // Inputs that never normalize to [6-9]\d{9}.
    const arbInvalid = fc.oneof(
      fc.constant(""),
      fc.constant("12345"),
      fc.constant("00000"),
      fc.string({ maxLength: 4 }),
      // 10+ digits starting with a disallowed leading digit.
      fc
        .array(fc.integer({ min: 0, max: 5 }), { minLength: 10, maxLength: 10 })
        .map((d) => d.join("")),
      fc.constant("abcdefghij")
    );

    await fc.assert(
      fc.asyncProperty(arbInvalid, async (raw) => {
        vi.mocked(findCustomerByMobile).mockResolvedValue([]);

        const result = await check(raw);

        expect(result.eligible).toBe(false);
        if (!result.eligible) {
          expect(result.reason).toBe("INVALID_FORMAT");
        }
        // Short-circuit before data access → the repository is never queried,
        // so no OTP/session could ever be triggered downstream.
        expect(findCustomerByMobile).not.toHaveBeenCalled();
      }),
      { numRuns: 25 }
    );
  });
});
